"""LangGraph tools for Slurm job management."""

from __future__ import annotations

from typing import Optional

from langchain_core.tools import tool
from pydantic import BaseModel, Field

from chem_copilot.parsers.output_parser import OutputParser
from chem_copilot.slurm.manager import SlurmManager


def _manager() -> SlurmManager:
    """Lazy singleton — config read from env at call time."""
    return SlurmManager()


# ------------------------------------------------------------------
# Submit
# ------------------------------------------------------------------

class SubmitFHIAimsInput(BaseModel):
    """Input schema for FHI-aims job submission."""
    control_in: str = Field(description="Contents of control.in (without species defaults)")
    geometry_in: str = Field(description="Contents of geometry.in")
    job_name: str = Field(default="aims", description="Slurm job name")
    basis_tier: str = Field(default="light", description="Basis tier for species defaults")
    partition: Optional[str] = Field(default=None, description="Slurm partition override")
    time_limit: Optional[str] = Field(default=None, description="Time limit, e.g. '4:00:00'")
    ntasks: Optional[int] = Field(default=None, description="Number of MPI tasks")
    cpus_per_task: Optional[int] = Field(default=None, description="CPUs per task")


@tool("submit_fhiaims_job", args_schema=SubmitFHIAimsInput)
def submit_fhiaims_job(
    control_in: str,
    geometry_in: str,
    job_name: str = "aims",
    basis_tier: str = "light",
    partition: Optional[str] = None,
    time_limit: Optional[str] = None,
    ntasks: Optional[int] = None,
    cpus_per_task: Optional[int] = None,
) -> str:
    """Submit an FHI-aims calculation to the Slurm cluster.

    Takes control.in and geometry.in contents (as generated by
    generate_fhiaims_input), writes them to a job directory,
    appends the appropriate species defaults, and submits via sbatch.

    Returns the Slurm job ID and job directory path.

    Use this when the user wants to actually run an FHI-aims calculation.
    """
    mgr = _manager()
    overrides: dict[str, str] = {}
    if partition:
        overrides["partition"] = partition
    if time_limit:
        overrides["time"] = time_limit
    if ntasks is not None:
        overrides["ntasks"] = str(ntasks)
    if cpus_per_task is not None:
        overrides["cpus_per_task"] = str(cpus_per_task)

    try:
        job_id = mgr.submit_fhiaims(
            control_in=control_in,
            geometry_in=geometry_in,
            job_name=job_name,
            basis_tier=basis_tier,
            slurm_overrides=overrides or None,
        )
        job_dir = mgr._find_job_dir(job_id)
        return f"Job submitted successfully.\nJob ID: {job_id}\nJob directory: {job_dir}"
    except Exception as e:
        return f"Job submission failed: {e}"


# ------------------------------------------------------------------
# Submit Psi4
# ------------------------------------------------------------------

class SubmitPsi4Input(BaseModel):
    """Input schema for Psi4 job submission."""
    input_script: str = Field(description="Psi4 Python input script content")
    job_name: str = Field(default="psi4", description="Slurm job name")
    psi4_env: str = Field(
        default="xdm",
        description="Psi4 environment: 'xdm' (XDM branch) or 'apbe0' (aPBE0 overlay)",
    )
    time_limit: Optional[str] = Field(default=None, description="Time limit, e.g. '4:00:00'")
    cpus_per_task: Optional[int] = Field(default=None, description="CPUs per task")


@tool("submit_psi4_job", args_schema=SubmitPsi4Input)
def submit_psi4_job(
    input_script: str,
    job_name: str = "psi4",
    psi4_env: str = "xdm",
    time_limit: Optional[str] = None,
    cpus_per_task: Optional[int] = None,
) -> str:
    """Submit a Psi4 calculation to the Slurm cluster.

    Takes a Psi4 Python input script (as generated by generate_psi4_input),
    writes it to a job directory, and submits via sbatch with the correct
    Psi4 conda environment (xdm or apbe0).

    Returns the Slurm job ID and job directory path.
    """
    mgr = _manager()
    overrides: dict[str, str] = {}
    if time_limit:
        overrides["time"] = time_limit
    if cpus_per_task is not None:
        overrides["cpus_per_task"] = str(cpus_per_task)

    try:
        job_id = mgr.submit_psi4(
            input_script=input_script,
            job_name=job_name,
            psi4_env=psi4_env,
            slurm_overrides=overrides or None,
        )
        job_dir = mgr._find_job_dir(job_id)
        return f"Psi4 job submitted successfully.\nJob ID: {job_id}\nJob directory: {job_dir}\nEnvironment: psi4-{psi4_env}"
    except Exception as e:
        return f"Psi4 job submission failed: {e}"


# ------------------------------------------------------------------
# Status
# ------------------------------------------------------------------

class CheckJobInput(BaseModel):
    """Input schema for job status check."""
    job_id: str = Field(description="Slurm job ID to check")


@tool("check_job_status", args_schema=CheckJobInput)
def check_job_status(job_id: str) -> str:
    """Check the status of a Slurm job.

    Returns the job state (PENDING, RUNNING, COMPLETED, FAILED, etc.),
    node, elapsed time, and output file location.

    Use this to check if a submitted calculation has finished.
    """
    mgr = _manager()
    info = mgr.get_job_status(job_id)

    lines = [
        f"Job ID: {info.job_id}",
        f"State: {info.state}",
    ]
    if info.name:
        lines.append(f"Name: {info.name}")
    if info.node:
        lines.append(f"Node: {info.node}")
    if info.elapsed:
        lines.append(f"Elapsed: {info.elapsed}")
    if info.exit_code:
        lines.append(f"Exit code: {info.exit_code}")
    if info.job_dir:
        lines.append(f"Directory: {info.job_dir}")
    if info.output_file:
        lines.append(f"Output file: {info.output_file}")

    return "\n".join(lines)


# ------------------------------------------------------------------
# List jobs
# ------------------------------------------------------------------

class ListJobsInput(BaseModel):
    """Input schema for listing jobs."""
    n: int = Field(default=10, description="Number of recent jobs to list")


@tool("list_recent_jobs", args_schema=ListJobsInput)
def list_recent_jobs(n: int = 10) -> str:
    """List recent jobs submitted through chem-copilot.

    Shows job ID, state, program, and directory for each job.
    """
    mgr = _manager()
    jobs = mgr.list_recent_jobs(n=n)

    if not jobs:
        return "No recent jobs found."

    lines = []
    for j in jobs:
        state_icon = {"COMPLETED": "+", "RUNNING": ">", "PENDING": "~", "FAILED": "X"}.get(
            j.state, "?"
        )
        lines.append(f"[{state_icon}] {j.job_id}  {j.state:<12s}  {j.name}  {j.job_dir}")

    return "\n".join(lines)


# ------------------------------------------------------------------
# Cancel
# ------------------------------------------------------------------

class CancelJobInput(BaseModel):
    """Input schema for job cancellation."""
    job_id: str = Field(description="Slurm job ID to cancel")


@tool("cancel_job", args_schema=CancelJobInput)
def cancel_job(job_id: str) -> str:
    """Cancel a running or pending Slurm job."""
    mgr = _manager()
    return mgr.cancel_job(job_id)


# ------------------------------------------------------------------
# Get result
# ------------------------------------------------------------------

class GetResultInput(BaseModel):
    """Input schema for result retrieval."""
    job_id: str = Field(description="Slurm job ID to get results for")


@tool("get_job_result", args_schema=GetResultInput)
def get_job_result(job_id: str) -> str:
    """Retrieve and parse the results of a completed calculation.

    Finds the output file for the given job ID, parses it using
    the appropriate parser (FHI-aims, Psi4, Gaussian), and returns
    a structured summary of the results.

    Use this after a job has COMPLETED to analyze the results.
    """
    mgr = _manager()

    # Check status first
    info = mgr.get_job_status(job_id)
    if info.state in ("PENDING", "RUNNING"):
        return f"Job {job_id} is still {info.state}. Wait for it to complete before retrieving results."

    output_path = mgr.get_output_path(job_id)
    if output_path is None:
        return f"No output file found for job {job_id}. Job state: {info.state}"

    program = mgr.get_program(job_id)
    parser = OutputParser()

    try:
        result = parser.parse_file(output_path, program=program)
    except Exception as e:
        return f"Failed to parse output for job {job_id}: {e}\nOutput file: {output_path}"

    lines = [
        f"Job {job_id} — {program} — {result.calc_type}",
        f"Status: {'CONVERGED' if result.success else 'FAILED/INCOMPLETE'}",
    ]

    e = result.energies
    if e.total_energy is not None:
        lines.append(f"Total energy: {e.total_energy:.8f} eV ({e.total_energy_hartree:.10f} Ha)")
    if e.scf_energies:
        lines.append(f"SCF iterations: {len(e.scf_energies)}")

    orb = result.orbitals
    if orb.homo_lumo_gap is not None:
        lines.append(f"HOMO-LUMO gap: {orb.homo_lumo_gap:.4f} eV")

    if result.forces.max_force is not None:
        lines.append(f"Max force: {result.forces.max_force:.6f} eV/Ang")

    opt = result.optimization
    if opt.n_steps > 1:
        lines.append(f"Optimization: {opt.n_steps} steps, converged={opt.converged}")

    if result.n_atoms:
        lines.append(f"Atoms: {result.n_atoms}")
    if result.n_basis_functions:
        lines.append(f"Basis functions: {result.n_basis_functions}")

    if result.warnings:
        lines.append("Warnings: " + "; ".join(result.warnings))

    lines.append(f"Output file: {output_path}")

    return "\n".join(lines)
