"""Psi4 input file generator.

Generates Psi4 Python input scripts from a molecule specification
and calculation parameters.
"""

from __future__ import annotations

from chem_copilot.models import (
    CalculationType,
    DispersionMethod,
    GeneratedInput,
    MoleculeSpec,
    Psi4Method,
    Psi4Params,
)

# Psi4 dispersion suffix appended to the method string (e.g., "b3lyp-d3bj").
_PSI4_DISPERSION_SUFFIX: dict[str, str] = {
    DispersionMethod.D3.value: "-d3",
    DispersionMethod.D3BJ.value: "-d3bj",
    DispersionMethod.D4.value: "-d4",
}

# Psi4 function call for each calculation type.
_CALC_FUNCTION: dict[CalculationType, str] = {
    CalculationType.SINGLE_POINT: "energy",
    CalculationType.OPTIMIZATION: "optimize",
    CalculationType.FREQUENCY: "frequency",
}


class Psi4Generator:
    """Generate Psi4 Python input scripts."""

    def generate(
        self,
        molecule: MoleculeSpec,
        params: Psi4Params | None = None,
    ) -> GeneratedInput:
        """Generate a Psi4 input script.

        Parameters
        ----------
        molecule : MoleculeSpec
            Molecular system specification (periodic systems not supported).
        params : Psi4Params, optional
            Calculation parameters. Defaults to HF/cc-pVDZ single point.

        Returns
        -------
        GeneratedInput
            Generated Python script, warnings, and a human-readable summary.
        """
        if params is None:
            params = Psi4Params()

        warnings: list[str] = []

        if molecule.is_periodic:
            warnings.append(
                "Psi4 does not support periodic boundary conditions. "
                "Lattice vectors will be ignored."
            )

        # Determine reference wavefunction
        reference = self._resolve_reference(molecule, params, warnings)

        # Build the method string
        method_str = self._method_string(params, warnings)

        script = self._build_script(molecule, params, method_str, reference, warnings)
        summary = self._build_summary(molecule, params, method_str)

        return GeneratedInput(
            files={"input.py": script},
            warnings=warnings,
            summary=summary,
        )

    # ------------------------------------------------------------------
    # Script generation
    # ------------------------------------------------------------------

    def _build_script(
        self,
        molecule: MoleculeSpec,
        params: Psi4Params,
        method_str: str,
        reference: str,
        warnings: list[str],
    ) -> str:
        lines: list[str] = []

        # Header
        lines.append('"""')
        lines.append(f"Psi4 input script — generated by chem-copilot")
        lines.append(f"Method: {method_str}/{params.basis}")
        lines.append('"""')
        lines.append("")
        lines.append("import psi4")
        lines.append("")

        # Resource settings
        lines.append("# Resources")
        lines.append(f"psi4.set_memory('{params.memory}')")
        lines.append(f"psi4.set_num_threads({params.num_threads})")
        lines.append("")

        # Molecule block
        geom_block = self._geometry_block(molecule, params)
        lines.append("mol = psi4.geometry('''")
        lines.append(geom_block)
        lines.append("''')")
        lines.append("")

        # Global options
        lines.append("psi4.set_options({")
        lines.append(f"    'basis': '{params.basis}',")
        lines.append(f"    'reference': '{reference}',")
        lines.append(f"    'scf_type': '{params.scf_type}',")
        lines.append(f"    'e_convergence': {params.e_convergence},")
        lines.append(f"    'd_convergence': {params.d_convergence},")
        lines.append(f"    'maxiter': {params.maxiter},")

        # Frozen core for correlated methods
        if params.method in (
            Psi4Method.MP2, Psi4Method.MP3,
            Psi4Method.CCSD, Psi4Method.CCSD_T,
        ):
            fc = "true" if params.frozen_core else "false"
            lines.append(f"    'freeze_core': '{fc}',")

        # Symmetry
        if params.symmetry:
            # Symmetry is set on the molecule, but we can also disable it globally
            if params.symmetry.lower() == "c1":
                lines.append("    'symmetry': 'c1',")

        # Extra user options
        for key, value in params.extra_options.items():
            lines.append(f"    '{key}': '{value}',")

        lines.append("})")
        lines.append("")

        # Calculation call
        calc_func = _CALC_FUNCTION.get(params.calculation_type)
        if calc_func is None:
            warnings.append(
                f"Calculation type '{params.calculation_type.value}' is not directly "
                "supported by Psi4's simple interface. Generating energy() call."
            )
            calc_func = "energy"

        return_var = "E" if calc_func == "energy" else "E, wfn"
        return_type = f"return_wfn=True" if calc_func != "energy" else ""

        if calc_func == "energy":
            lines.append(f"E = psi4.energy('{method_str}')")
        elif calc_func == "optimize":
            lines.append(f"E, wfn = psi4.optimize('{method_str}', return_wfn=True)")
        elif calc_func == "frequency":
            lines.append(f"E, wfn = psi4.frequency('{method_str}', return_wfn=True)")

        lines.append("")
        lines.append(f"psi4.core.print_out(f'\\nFinal energy: {{E:.12f}} Hartree\\n')")

        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Geometry block
    # ------------------------------------------------------------------

    def _geometry_block(self, molecule: MoleculeSpec, params: Psi4Params) -> str:
        """Build the Psi4 molecule specification block."""
        lines: list[str] = []

        # Charge and multiplicity line
        lines.append(f"{molecule.charge} {molecule.multiplicity}")

        # Atom coordinates
        symbols, coords = molecule.to_symbols_coords()
        for sym, xyz in zip(symbols, coords):
            lines.append(f"{sym}  {xyz[0]:14.8f}  {xyz[1]:14.8f}  {xyz[2]:14.8f}")

        # Symmetry
        if params.symmetry:
            lines.append(f"symmetry {params.symmetry}")
        lines.append("no_reorient")
        lines.append("no_com")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Method string
    # ------------------------------------------------------------------

    def _method_string(self, params: Psi4Params, warnings: list[str]) -> str:
        """Build the Psi4 method string, e.g., 'b3lyp-d3bj' or 'ccsd(t)'."""
        if params.method == Psi4Method.DFT:
            base = params.functional or "pbe"
        elif params.method == Psi4Method.CCSD_T:
            base = "ccsd(t)"
        else:
            base = params.method.value

        # Append dispersion suffix for DFT
        if params.dispersion != DispersionMethod.NONE:
            suffix = _PSI4_DISPERSION_SUFFIX.get(params.dispersion.value)
            if suffix:
                base += suffix
            else:
                warnings.append(
                    f"Dispersion method '{params.dispersion.value}' is not directly "
                    "supported as a Psi4 suffix. Use extra_options or an external tool."
                )

        return base

    # ------------------------------------------------------------------
    # Reference wavefunction
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_reference(
        molecule: MoleculeSpec,
        params: Psi4Params,
        warnings: list[str],
    ) -> str:
        """Determine the SCF reference wavefunction."""
        if params.reference:
            return params.reference

        if molecule.multiplicity > 1:
            # Open-shell: UHF by default, ROHF for coupled-cluster
            if params.method in (Psi4Method.CCSD, Psi4Method.CCSD_T):
                warnings.append(
                    "Open-shell coupled-cluster: using ROHF reference. "
                    "Consider whether UHF or ROHF is appropriate for your system."
                )
                return "rohf"
            return "uhf"

        return "rhf"

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def _build_summary(
        self,
        molecule: MoleculeSpec,
        params: Psi4Params,
        method_str: str,
    ) -> str:
        symbols, _ = molecule.to_symbols_coords()
        formula = _hill_formula(symbols)
        parts = [
            f"Psi4 {params.calculation_type.value}",
            f"{formula} ({len(symbols)} atoms)",
            f"{method_str}/{params.basis}",
        ]
        if molecule.charge != 0:
            parts.append(f"charge={molecule.charge}")
        if molecule.multiplicity > 1:
            parts.append(f"mult={molecule.multiplicity}")
        return " | ".join(parts)


def _hill_formula(symbols: list[str]) -> str:
    """Molecular formula in Hill system."""
    counts: dict[str, int] = {}
    for s in symbols:
        counts[s] = counts.get(s, 0) + 1
    parts: list[str] = []
    for elem in ["C", "H"]:
        if elem in counts:
            n = counts.pop(elem)
            parts.append(f"{elem}{n}" if n > 1 else elem)
    for elem in sorted(counts):
        n = counts[elem]
        parts.append(f"{elem}{n}" if n > 1 else elem)
    return "".join(parts)
